#!/usr/bin/env bash
# Lorentz: A black hole for Internet advertisements
# (c) 2026 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Lorentz Engine
# Embeds a directory tree (the web UI's static export, web/out) into a single
# generated C source file: one byte array per file plus a webui_files[]
# lookup table (struct webui_file, declared in webui.h) that webui_handler()
# serves from memory. Invoked by CMakeLists.txt at build time, after `npm run
# build:embed` has produced $1.
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.
set -euo pipefail

OUT_DIR="$1"
DEST="$2"

if [ ! -d "$OUT_DIR" ]; then
	echo "generate.sh: $OUT_DIR does not exist (web UI static export missing)" >&2
	exit 1
fi

mime_type() {
	case "$1" in
		*.html) echo "text/html" ;;
		*.css) echo "text/css" ;;
		*.js|*.mjs) echo "application/javascript" ;;
		*.json|*.webmanifest) echo "application/json" ;;
		*.svg) echo "image/svg+xml" ;;
		*.png) echo "image/png" ;;
		*.jpg|*.jpeg) echo "image/jpeg" ;;
		*.gif) echo "image/gif" ;;
		*.ico) echo "image/x-icon" ;;
		*.woff2) echo "font/woff2" ;;
		*.woff) echo "font/woff" ;;
		*.ttf) echo "font/ttf" ;;
		*.txt|*.map) echo "text/plain" ;;
		*) echo "application/octet-stream" ;;
	esac
}

TMP="${DEST}.tmp"
{
	echo "// Generated by src/api/webui/generate.sh from web/out - do not edit."
	echo "#include \"api/webui/webui.h\""
} > "$TMP"

paths=()
mimes=()
vars=()
i=0

while IFS= read -r -d '' file; do
	rel="${file#"$OUT_DIR"/}"
	var="wf_$i"
	# xxd also emits a "<var>_len" unsigned int; dropped since the table below
	# uses sizeof(<var>) instead, which -Wunused-const-variable would else flag.
	xxd -i -n "$var" "$file" | sed -e '/^unsigned int /d' -e 's/^unsigned /static const unsigned /' >> "$TMP"
	paths+=("$rel")
	mimes+=("$(mime_type "$rel")")
	vars+=("$var")
	i=$((i + 1))
done < <(find "$OUT_DIR" -type f -print0 | sort -z)

{
	echo "const struct webui_file webui_files[] = {"
	for idx in "${!paths[@]}"; do
		printf '\t{ "%s", "%s", %s, sizeof(%s) },\n' \
			"${paths[$idx]}" "${mimes[$idx]}" "${vars[$idx]}" "${vars[$idx]}"
	done
	echo "};"
	echo "const size_t webui_files_count = sizeof(webui_files) / sizeof(webui_files[0]);"
} >> "$TMP"

mv "$TMP" "$DEST"
